# ref. https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = false
fn_args_layout = "Tall"
fn_call_width = 60
fn_single_line = false
force_explicit_abi =  true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
max_width = 100
normalize_doc_attributes = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
where_single_line = false
wrap_comments = true