---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Auto Scaling Groups for amd64"

# takes about 2-minute for 3 nodes

# TODO: support CloudWatch logs
# ref. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
# ref. https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  Id:
    Type: String
    Description: Unique identifier, prefix for all resources created below.

  NodeType:
    Type: String
    AllowedValues: ["beacon", "non-beacon"]
    Description: Node type.

  KmsCmkArn:
    Type: String
    Description: KMS CMK ARN that de/encrypts resources.

  S3BucketName:
    Type: String
    Description: S3 bucket name.

  Ec2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 SSH key name

  InstanceProfileArn:
    Type: String
    Description: Instance profile ARN

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The public subnet IDs where node instances are to be created.

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: EC2 security group ID

  ImageId:
    Type: String
    Default: ""
    Description: (Optional) Custom image ID. This value overrides any AWS Systems Manager Parameter Store value specified above.

  # https://ubuntu.com/server/docs/cloud-images/amazon-ec2
  # TODO: support arm64
  ImageIdSsmParameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID.

  # Avalanche consensus paper used "c5.large" for testing 125 ~ 2,000 nodes
  # Avalanche test net runs "c5.2xlarge".
  #
  # https://aws.amazon.com/ec2/instance-types/m5/
  # m5.large:   2 vCPU + 8  GiB RAM
  # m5.xlarge:  4 vCPU + 16 GiB RAM
  # m5.2xlarge: 8 vCPU + 32 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/c5/
  # c5.large:   2 vCPU + 4  GiB RAM
  # c5.xlarge:  4 vCPU + 8  GiB RAM
  # c5.2xlarge: 8 vCPU + 16 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/r5/
  # r5.large:   2 vCPU + 16 GiB RAM
  # r5.xlarge:  4 vCPU + 32 GiB RAM
  # r5.2xlarge: 8 vCPU + 64 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/t3/
  # t3.large:   2 vCPU + 8 GiB RAM
  # t3.xlarge:  4 vCPU + 16 GiB RAM
  # t3.2xlarge: 8 vCPU + 32 GiB RAM
  #
  InstanceTypes:
    Type: CommaDelimitedList
    Default: m5.large,c5.large,r5.large,t3.large
    # Default: m5.xlarge,c5.xlarge,r5.xlarge,t3.xlarge
    # Default: m5.2xlarge,c5.2xlarge,r5.2xlarge,t3.2xlarge
    Description: EC2 instance types

  InstanceTypesCount:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 4
    Description: The number of instance types

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumetype
  VolumeType:
    Type: String
    Default: gp3
    Description: Volume type.

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumesize
  VolumeSize:
    Type: Number
    Default: 100
    MinValue: 40
    MaxValue: 1024
    Description: Size of the root disk for the EC2 instances, in GiB.

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-iops
  VolumeIops:
    Type: Number
    Default: 3000
    Description: The number of I/O operations per second (IOPS).

  # only for gp3
  # https://aws.amazon.com/ebs/volume-types/
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput
  # "1000" does not work -- "InvalidParameterValue - Throughput (MiBps) to iops ratio of 0.333333 is too high; maximum is 0.250000 MiBps per iops."
  VolumeThroughput:
    Type: Number
    Default: 500
    Description: The throughput to provision for a gp3 volume, with a maximum of 1,000 MiB/s.

  AsgMinSize:
    Type: Number
    Description: Minimum size auto scaling group
    Default: 1
    MinValue: 1
    MaxValue: 1000

  AsgMaxSize:
    Type: Number
    Description: Maximum size auto scaling group
    Default: 10
    MinValue: 1
    MaxValue: 1000

  AsgDesiredCapacity:
    Type: Number
    Description: Desired size auto scaling group
    Default: 5
    MinValue: 1
    MaxValue: 1000

Conditions:
  HasImageId:
    Fn::Not:
      - Fn::Equals:
          - Ref: ImageId
          - ""

  Has2InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 2
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has3InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has4InstanceTypes:
    Fn::Equals:
      - Ref: InstanceTypesCount
      - 4

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:
        !Join ["-", [!Ref Id, "asg-launch-template", !Ref NodeType, "amd64"]]
      LaunchTemplateData:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-iaminstanceprofile.html
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        ImageId:
          Fn::If:
            - HasImageId
            - !Ref ImageId
            - !Ref ImageIdSsmParameter
        KeyName: !Ref Ec2KeyPairName

        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping.html
        BlockDeviceMappings:
          - DeviceName: "/dev/xvdb"
            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
            Ebs:
              VolumeType: !Ref VolumeType
              VolumeSize: !Ref VolumeSize
              Iops: !Ref VolumeIops
              Throughput: !Ref VolumeThroughput
              DeleteOnTermination: true
              Encrypted: true
        Monitoring:
          Enabled: true

        # need this for public DNS + SSH access
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - !Ref SecurityGroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub "${Id}-instance-${NodeType}-amd64" }
          - ResourceType: volume
            Tags:
              - { Key: Name, Value: !Sub "${Id}-volume-${NodeType}-amd64" }

        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-userdata
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
        # /var/log/cloud-init-output.log
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              set -xeu

              export DEBIAN_FRONTEND=noninteractive
              sudo apt-get update -y && sudo apt-get upgrade -y \
              && sudo apt-get install -y \
                  curl wget unzip zip gzip tar libssl-dev \
                  python3-pip python-setuptools

              TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
              INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" --retry 3 -s http://169.254.169.254/latest/meta-data/instance-id)
              ATTACHMENT_STATE="unknown"
              until [ "$ATTACHMENT_STATE" == "attached" ]; do
                ATTACHMENT_STATE=$(aws ec2 describe-volumes \
                      --region ${AWS::Region} \
                      --filters \
                        Name=attachment.instance-id,Values=$INSTANCE_ID \
                        Name=attachment.device,Values=/dev/nvme1n1 \
                      --query Volumes[].Attachments[].State \
                      --output text)
                sleep 2
              done

              # TODO: why device name is not "/dev/xvdb"?
              lsblk
              df -h
              sudo mkfs -t ext4 /dev/nvme1n1
              mkdir -p /avalanche-data
              sudo mount /dev/nvme1n1 /avalanche-data -t ext4
              # auto remount in case of instance reboot
              sudo echo '/dev/nvme1n1       /avalanche-data   ext4    defaults,nofail 0       2' >> /etc/fstab
              mount -a
              lsblk
              df -h

              curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscli.v2.zip
              unzip awscli.v2.zip
              sudo ./aws/install
              /usr/local/bin/aws --version
              aws s3 ls s3://${S3BucketName}/${Id}/
              aws s3 cp s3://${S3BucketName}/${Id}/install/avalanched /tmp/avalanched
              chmod +x /tmp/avalanched
              mv /tmp/avalanched /usr/local/bin/avalanched

              mkdir -p /etc/pki/tls/certs
              chmod 755 /etc/pki/tls/certs
              cat > /tmp/avalanched.service <<EOF
              [Unit]
              Description=avalanche agent
              [Service]
              Type=notify
              Restart=always
              RestartSec=5s
              LimitNOFILE=40000
              ExecStart=/usr/local/bin/avalanched \
                --log-level info \
                --region ${AWS::Region} \
                --tls-key-path /etc/pki/tls/certs/avalanched.pki.key \
                --tls-cert-path /etc/pki/tls/certs/avalanched.pki.crt \
                --avalanche-bin /usr/local/bin/avalanche
              [Install]
              WantedBy=multi-user.target
              EOF
              sudo mv /tmp/avalanched.service /etc/systemd/system/avalanched.service
              # sudo systemctl status avalanched.service -l --no-pager
              # sudo journalctl -u avalanched.service -l --no-pager|less
              # sudo journalctl -f -u avalanched.service
              sudo systemctl daemon-reload
              sudo systemctl enable avalanched.service
              sudo systemctl restart avalanched.service

              # https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu.html
              sudo snap install amazon-ssm-agent --classic
              sudo systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
              sudo systemctl restart snap.amazon-ssm-agent.amazon-ssm-agent.service
              mkdir -p /etc/systemd/system/snap.amazon-ssm-agent.amazon-ssm-agent.service.d
              cat > /etc/systemd/system/snap.amazon-ssm-agent.amazon-ssm-agent.service.d/10-restart-always.conf <<EOF
              [Service]
              Restart=always
              RestartSec=60s
              EOF
              sudo systemctl restart snap.amazon-ssm-agent.amazon-ssm-agent.service

              # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
              curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -o /tmp/awslogs-agent-setup.py
              sudo python3 /tmp/awslogs-agent-setup.py --region ${AWS::Region}

              curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz -o /tmp/aws-cfn-bootstrap-latest.tar.gz
              pip install /tmp/aws-cfn-bootstrap-latest.tar.gz
              if [[ $? -ne 0 ]]; then
                /usr/local/bin/cfn-signal --resource AutoScalingGroup \
                  --stack ${AWS::StackName} \
                  --region ${AWS::Region} \
                  --success false
              else
                /usr/local/bin/cfn-signal -e $? --resource AutoScalingGroup \
                  --stack ${AWS::StackName} \
                  --region ${AWS::Region}
              fi

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref AsgMinSize
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Properties:
      AutoScalingGroupName:
        !Join ["-", [!Ref Id, "asg", !Ref NodeType, "amd64"]]
      MinSize: !Ref AsgMinSize
      MaxSize: !Ref AsgMaxSize
      DesiredCapacity: !Ref AsgDesiredCapacity
      VPCZoneIdentifier: !Ref PublicSubnetIds
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      MetricsCollection:
        - Granularity: "1Minute"
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: !Join ["-", [!Ref Id, "asg", !Ref NodeType, "amd64"]]
        - Key: ID
          PropagateAtLaunch: true
          Value: !Ref Id
        - Key: NODE_TYPE
          PropagateAtLaunch: true
          Value: !Ref NodeType
        - Key: KMS_CMK_ARN
          PropagateAtLaunch: true
          Value: !Ref KmsCmkArn
        - Key: S3_BUCKET_NAME
          PropagateAtLaunch: true
          Value: !Ref S3BucketName
      # specify "MixedInstancesPolicy" or "LaunchConfiguration"
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandAllocationStrategy: "prioritized"
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref ASGLaunchTemplate
            Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: !Select [0, !Ref InstanceTypes]
            - Fn::If:
                - Has2InstanceTypes
                - InstanceType: !Select [1, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has3InstanceTypes
                - InstanceType: !Select [2, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has4InstanceTypes
                - InstanceType: !Select [3, !Ref InstanceTypes]
                - !Ref AWS::NoValue

Outputs:
  # same as "AutoScalingGroupName"
  AsgLogicalId:
    Value: !Ref ASG
