---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS IAM instance role"

# takes about 3-minute
Parameters:
  Id:
    Type: String
    Description: Unique identifier, prefix for all resources created below.

  KMSKeyArn:
    Type: String
    Description: The CMK ARN that de/encrypts resources in S3.

  S3BucketName:
    Type: String
    Description: S3 bucket name to store.

Mappings:
  ServicePrincipals:
    aws-cn:
      ec2: ec2.amazonaws.com.cn
    aws:
      ec2: ec2.amazonaws.com

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref Id, "instance-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - Fn::FindInMap:
                    - ServicePrincipals
                    - Ref: AWS::Partition
                    - ec2
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: avalanche-ops-instance-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeTags # to find network/resource information
                Resource: "*"
              - Effect: Allow
                Action:
                  - kms:Encrypt # to generate TLS key and encrypt
                  - kms:GenerateDataKey* # to encrypt TLS key
                  - kms:DescribeKey # to describe the CMK
                Resource: { Ref: KMSKeyArn }
              - Effect: Allow
                Action:
                  - s3:GetObject # to download avalanched-aws binary
                  - s3:PutObject # to upload generated TLS keys
                Resource:
                  - !Join [
                      "",
                      [!Sub "arn:${AWS::Partition}:s3:::", !Ref S3BucketName],
                    ]
                  - !Join [
                      "",
                      [
                        !Sub "arn:${AWS::Partition}:s3:::",
                        !Ref S3BucketName,
                        "/installation/*",
                      ],
                    ]
                  - !Join [
                      "",
                      [
                        !Sub "arn:${AWS::Partition}:s3:::",
                        !Ref S3BucketName,
                        "/",
                        !Ref Id,
                        "/*",
                      ],
                    ]
                  - !Join [
                      "",
                      [
                        !Sub "arn:${AWS::Partition}:s3:::",
                        !Ref S3BucketName,
                        "/",
                        !Ref Id,
                        "/pki/*",
                      ],
                    ]

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join ["-", [!Ref Id, "instance-profile"]]
      Path: "/"
      Roles:
        - !Ref InstanceRole

Outputs:
  InstanceRoleARN:
    Value: !GetAtt InstanceRole.Arn
    Description: Role ARN

  InstanceProfileARN:
    Value: !GetAtt InstanceProfile.Arn
    Description: Instance profile ARN
