---
AWSTemplateFormatVersion: "2010-09-09"
Description: "SSM document to restart Avalanche node process to load chain config"

Parameters:
  DocumentName:
    Type: String
    Default: RestartAvalancheNodeChainConfigV0
    Description: SSM document Name.

  # e.g., avalanchego_config.chain_config_dir).join("...")
  ChainConfigDirectory:
    Type: String
    Default: /data/avalanche-configs/chains
    Description: Chain configuration directory (e.g., /data/avalanche-configs/chains/C/config.json)

  PlaceHolderWhitelistedSubnetId:
    Type: String
    Default: hac2sQTf29JJvveiJssb4tz8TNRQ3SyKSW7GgcwGTMk3xabgf
    Description: Whitelisted subnet Id that was used as a placeholder.

  NewBlockchainId:
    Type: String
    Default: ""
    Description: New subnet id to whitelist.

Resources:
  RestartAvalancheNodeChainConfig:
    # https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: !Ref DocumentName
      Tags:
        - Key: DocumentName
          Value: !Ref DocumentName
        - Key: DocumentVersion
          Value: "v0"
      Content:
        schemaVersion: "2.2"
        description: restartAvalancheNodeChainConfig
        parameters:
          executionTimeout:
            type: String
            description: "timeout for run on all instances"
            default: "50000"
          scriptTimeout:
            type: String
            description: "timeout for script on individual instance"
            default: "3600"
          chainConfigDirectory:
            type: String
            description: Chain configuration directory (e.g., /data/avalanche-configs/chains/C/config.json).
            default: !Ref ChainConfigDirectory
          placeHolderWhitelistedSubnetId:
            type: String
            description: Whitelisted subnet Id that was used as a placeholder.
            default: !Ref PlaceHolderWhitelistedSubnetId
          newBlockchainId:
            type: String
            description: New blockchain id to move configuration to.
            default: !Ref NewBlockchainId
        mainSteps:
          - action: aws:runShellScript
            name: restartAvalancheNodeChainConfig
            inputs:
              timeoutSeconds: "{{ scriptTimeout }}"
              runCommand:
                - |
                  #!/bin/bash
                  set -xeu

                  # do not use bash/sed hacks....
                  /usr/local/bin/avalanche-config --version

                  # assume "avalanched" already wrote chain config based on place holder whitelisted subnet id
                  # TODO: implement with "avalanche-config"
                  sudo cp -rf {{ chainConfigDirectory }}/{{ placeHolderWhitelistedSubnetId }} {{ chainConfigDirectory }}/{{ newBlockchainId }}
                  sudo cat {{ chainConfigDirectory }}/{{ newBlockchainId }}/config.json

                  sudo systemctl restart avalanche
                  sleep 5
                  sudo tail -50 /var/log/avalanche/avalanche.log || true
                  # sudo tail -100 /var/log/avalanche/avalanche.log | grep {{ newBlockchainId }}

                  # to check the status
                  # sudo find /var/log/avalanche/
                  # sudo tail /var/log/avalanche/avalanche.log
