---
AWSTemplateFormatVersion: "2010-09-09"
Description: "SSM document to restart Avalanche node process to load chain config"

Parameters:
  DocumentName:
    Type: String
    Default: RestartAvalancheNodeChainConfigV0
    Description: SSM document Name.

Resources:
  RestartAvalancheNodeChainConfig:
    # https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: !Ref DocumentName
      Tags:
        - Key: DocumentName
          Value: !Ref DocumentName
        - Key: DocumentVersion
          Value: "v1"
      Content:
        schemaVersion: "2.2"
        description: restartAvalancheNodeChainConfig
        parameters:
          executionTimeout:
            type: String
            description: "timeout for run on all instances"
            default: "50000"
          scriptTimeout:
            type: String
            description: "timeout for script on individual instance"
            default: "3600"
          specPath:
            type: String
            description: avalancheup spec path (e.g., /data/avalancheup.yaml).
          subnetEvmName:
            type: String
            description: Name of subnet-evm in "Spec.subnet_evms".
          newBlockchainId:
            type: String
            description: New blockchain id to move configuration to.
        mainSteps:
          - action: aws:runShellScript
            name: restartAvalancheNodeChainConfig
            inputs:
              timeoutSeconds: "{{ scriptTimeout }}"
              runCommand:
                - |
                  #!/bin/bash
                  set -xeu

                  # to not use bash/sed hacks....
                  /usr/local/bin/avalanche-config --version
                  # to write subnet/chain config
                  /usr/local/bin/avalanched --version

                  # use "avalanched" to write chain config based on spec and new blockchain-id
                  /usr/local/bin/avalanched \
                  sync-subnet-evm-chain-config \
                  --log-level info \
                  --spec-file-path {{ specPath }} \
                  --subnet-evm-name {{ subnetEvmName }} \
                  --blockchain-id {{ newBlockchainId }}

                  sudo systemctl restart avalanche
                  sleep 5
                  sudo tail -50 /var/log/avalanche/avalanche.log || true
                  # sudo tail -100 /var/log/avalanche/avalanche.log | grep {{ newBlockchainId }}

                  # to check the status
                  # sudo find /var/log/avalanche/
                  # sudo tail /var/log/avalanche/avalanche.log
