---
AWSTemplateFormatVersion: "2010-09-09"
Description: "SSM document to restart Avalanche node process to track subnet"

Parameters:
  DocumentName:
    Type: String
    Default: RestartWithTrackedSubnetV1SubnetEvm
    Description: SSM document Name.

Resources:
  RestartAvalancheNodeTrackedSubnet:
    # https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: !Ref DocumentName
      Tags:
        - Key: DocumentName
          Value: !Ref DocumentName
        - Key: DocumentVersion
          Value: "v1"
      Content:
        schemaVersion: "2.2"
        description: RestartWithTrackedSubnet
        parameters:
          executionTimeout:
            type: String
            description: "timeout for run on all instances"
            default: "50000"
          scriptTimeout:
            type: String
            description: "timeout for script on individual instance"
            default: "3600"
          # e.g., "srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy"
          vmId:
            type: String
            description: Vm Id (must match with the binary path), used for making sure vm binary works!
          specPath:
            type: String
            description: avalancheup spec path (e.g., /data/avalancheup.yaml).
          subnetEvmName:
            type: String
            description: Name of subnet-evm in "Spec.subnet_evms".
          newTrackedSubnetId:
            type: String
            description: New subnet id to track.
        mainSteps:
          - action: aws:runShellScript
            name: RestartWithTrackedSubnet
            inputs:
              timeoutSeconds: "{{ scriptTimeout }}"
              runCommand:
                - |
                  #!/bin/bash
                  set -xeu

                  # to not use bash/sed hacks....
                  /usr/local/bin/avalanche-config --version
                  # to write subnet/chain config
                  /usr/local/bin/avalanched --version

                  # sudo systemctl cat avalanche
                  /usr/local/bin/plugin/{{ vmId }} --version

                  # to replace the avalanche configuration
                  # sudo cat /data/avalanche-configs/config.json
                  /usr/local/bin/avalanche-config add-track-subnet \
                  --log-level info \
                  --skip-prompt \
                  --config-file-path=/data/avalanche-configs/config.json \
                  --subnet-id {{ newTrackedSubnetId }}

                  cat /data/avalanche-configs/config.json

                  # use "avalanched" to write subnet config based on spec and new subnet-id
                  /usr/local/bin/avalanched \
                  sync-subnet-evm-subnet-config \
                  --log-level info \
                  --spec-file-path {{ specPath }} \
                  --subnet-evm-name {{ subnetEvmName }} \
                  --subnet-id {{ newTrackedSubnetId }}

                  sudo systemctl restart avalanche
                  sleep 5
                  sudo tail -50 /var/log/avalanche/avalanche.log || true
                  # sudo tail -100 /var/log/avalanche/avalanche.log | grep {{ newTrackedSubnetId }}

                  # to check the status
                  # sudo find /var/log/avalanche/
                  # sudo tail /var/log/avalanche/avalanche.log
