---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Development machine (amd64)"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  Id:
    Type: String
    Description: Unique identifier, prefix for all resources created below.

  KmsCmkArn:
    Type: String
    Description: KMS CMK ARN that de/encrypts resources.

  S3BucketName:
    Type: String
    Description: S3 bucket name.

  Ec2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 SSH key name

  InstanceProfileArn:
    Type: String
    Description: Instance profile ARN

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The public subnet IDs where node instances are to be created.

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: EC2 security group ID

  ImageId:
    Type: String
    Default: ""
    Description: (Optional) Custom image ID. This value overrides any AWS Systems Manager Parameter Store value specified above.

  # https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/
  ImageIdSsmParameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID.

  Arch:
    Type: String
    Default: "amd64"
    Description: The name of the architecture.

  # Avalanche consensus paper used "c5.large" for testing 125 ~ 2,000 nodes
  # Avalanche test net ("fuji") runs "c5.2xlarge"
  #
  # https://aws.amazon.com/ec2/instance-types/c6a/
  # c6a.large:   2 vCPU + 4  GiB RAM
  # c6a.xlarge:  4 vCPU + 8  GiB RAM
  # c6a.2xlarge: 8 vCPU + 16 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/m6a/
  # m6a.large:   2 vCPU + 8  GiB RAM
  # m6a.xlarge:  4 vCPU + 16 GiB RAM
  # m6a.2xlarge: 8 vCPU + 32 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/m5/
  # m5.large:   2 vCPU + 8  GiB RAM
  # m5.xlarge:  4 vCPU + 16 GiB RAM
  # m5.2xlarge: 8 vCPU + 32 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/c5/
  # c5.large:   2 vCPU + 4  GiB RAM
  # c5.xlarge:  4 vCPU + 8  GiB RAM
  # c5.2xlarge: 8 vCPU + 16 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/r5/
  # r5.large:   2 vCPU + 16 GiB RAM
  # r5.xlarge:  4 vCPU + 32 GiB RAM
  # r5.2xlarge: 8 vCPU + 64 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/t3/
  # t3.large:   2 vCPU + 8 GiB RAM
  # t3.xlarge:  4 vCPU + 16 GiB RAM
  # t3.2xlarge: 8 vCPU + 32 GiB RAM
  #
  InstanceTypes:
    Type: CommaDelimitedList
    Default: c6a.large,m6a.large,m5.large,c5.large
    Description: EC2 instance types

  InstanceTypesCount:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 4
    Description: The number of instance types

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumetype
  VolumeType:
    Type: String
    Default: gp3
    Description: Volume type.

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumesize
  VolumeSize:
    Type: Number
    Default: 400
    MinValue: 40
    MaxValue: 1024
    Description: Size of the root disk for the EC2 instances, in GiB.

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-iops
  VolumeIops:
    Type: Number
    Default: 3000
    Description: The number of I/O operations per second (IOPS).

  # only for gp3
  # https://aws.amazon.com/ebs/volume-types/
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput
  # "1000" does not work -- "InvalidParameterValue - Throughput (MiBps) to iops ratio of 0.333333 is too high; maximum is 0.250000 MiBps per iops."
  VolumeThroughput:
    Type: Number
    Default: 500
    Description: The throughput to provision for a gp3 volume, with a maximum of 1,000 MiB/s.

  AsgMinInstancesInService:
    Type: Number
    Description: Minimum instances in service for update.
    Default: 1
    MinValue: 1
    MaxValue: 1000

  AsgMinSize:
    Type: Number
    Description: Minimum size auto scaling group
    Default: 0
    MinValue: 0
    MaxValue: 1000

  AsgMaxSize:
    Type: Number
    Description: Maximum size auto scaling group
    Default: 2
    MinValue: 1
    MaxValue: 3

  AsgDesiredCapacity:
    Type: Number
    Description: Desired size auto scaling group
    Default: 1
    MinValue: 1
    MaxValue: 3

Conditions:
  HasImageId:
    Fn::Not:
      - Fn::Equals:
          - Ref: ImageId
          - ""

  Has2InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 2
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has3InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has4InstanceTypes:
    Fn::Equals:
      - Ref: InstanceTypesCount
      - 4

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Join ["-", [!Ref Id, !Ref Arch]]
      LaunchTemplateData:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-iaminstanceprofile.html
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        ImageId:
          Fn::If:
            - HasImageId
            - !Ref ImageId
            - !Ref ImageIdSsmParameter
        KeyName: !Ref Ec2KeyPairName

        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping.html
        BlockDeviceMappings:
          - DeviceName: "/dev/xvdb"
            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
            Ebs:
              VolumeType: !Ref VolumeType
              VolumeSize: !Ref VolumeSize
              Iops: !Ref VolumeIops
              Throughput: !Ref VolumeThroughput
              DeleteOnTermination: true
              Encrypted: true
        Monitoring:
          Enabled: true

        # need this for public DNS + SSH access
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - !Ref SecurityGroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub "${Id}-${Arch}" }
          - ResourceType: volume
            Tags:
              - { Key: Name, Value: !Sub "${Id}-${Arch}" }

        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-userdata
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
        # /var/log/cloud-init-output.log
        # takes about 3-minute
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              set -xeu

              sudo yum update -y && sudo yum upgrade -y
              sudo yum install -y \
              tmux \
              curl wget \
              tar unzip \
              git gcc \
              graphviz \
              python3-pip \
              openssl-devel \
              chrony \
              yum-utils device-mapper-persistent-data lvm2 \
              amazon-linux-extras

              sudo chkconfig chronyd on
              cat <<EOF | sudo tee -a /etc/chrony.conf
              # enables kernel synchronisation
              rtcsync
              EOF

              amazon-linux-extras
              sudo amazon-linux-extras enable vim=latest epel docker=latest
              sudo amazon-linux-extras install -y vim epel docker
              sudo systemctl daemon-reload
              sudo systemctl start --no-block docker
              sleep 2
              sudo systemctl status docker --full --no-pager || true
              sudo chmod 666 /var/run/docker.sock
              docker ps

              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscli.v2.zip
              unzip awscliv2.zip
              sudo ./aws/install
              /usr/local/bin/aws --version
              aws s3 ls s3://${S3BucketName}/

              # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html
              sudo yum install -y https://s3.${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_${Arch}/amazon-ssm-agent.rpm
              sudo systemctl enable amazon-ssm-agent || true
              sudo systemctl start --no-block amazon-ssm-agent
              sudo systemctl status amazon-ssm-agent

              TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
              INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" --retry 3 -s http://169.254.169.254/latest/meta-data/instance-id)
              ATTACHMENT_STATE="unknown"
              until [ "$ATTACHMENT_STATE" == "attached" ]; do
                ATTACHMENT_STATE=$(aws ec2 describe-volumes \
                      --region ${AWS::Region} \
                      --filters \
                        Name=attachment.instance-id,Values=$INSTANCE_ID \
                        Name=attachment.device,Values=/dev/xvdb \
                      --query Volumes[].Attachments[].State \
                      --output text)
                sleep 5
              done

              # TODO: why device name is not "/dev/xvdb"?
              sudo mkfs -t ext4 /dev/nvme1n1
              mkdir -p /data
              sudo mount /dev/nvme1n1 /data -t ext4
              # auto remount in case of instance reboot
              sudo echo '/dev/nvme1n1       /data   ext4    defaults,nofail 0       2' >> /etc/fstab
              sudo mount --all
              lsblk
              df -h

              # TODO: install Rust/Go for all users
              # TODO: signal instance ready

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref AsgMinInstancesInService
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Properties:
      AutoScalingGroupName: !Join ["-", [!Ref Id, !Ref Arch]]
      MinSize: !Ref AsgMinSize
      MaxSize: !Ref AsgMaxSize
      DesiredCapacity: !Ref AsgDesiredCapacity
      VPCZoneIdentifier: !Ref PublicSubnetIds
      HealthCheckType: EC2
      HealthCheckGracePeriod: 120
      MetricsCollection:
        - Granularity: "1Minute"
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: !Join ["-", [!Ref Id, !Ref Arch]]
        - Key: ID
          PropagateAtLaunch: true
          Value: !Ref Id
        - Key: KMS_CMK_ARN
          PropagateAtLaunch: true
          Value: !Ref KmsCmkArn
        - Key: S3_BUCKET_NAME
          PropagateAtLaunch: true
          Value: !Ref S3BucketName
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-mixedinstancespolicy.html
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandAllocationStrategy: "prioritized"
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplate.html
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref ASGLaunchTemplate
            Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplateoverrides.html
          Overrides:
            - InstanceType: !Select [0, !Ref InstanceTypes]
            - Fn::If:
                - Has2InstanceTypes
                - InstanceType: !Select [1, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has3InstanceTypes
                - InstanceType: !Select [2, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has4InstanceTypes
                - InstanceType: !Select [3, !Ref InstanceTypes]
                - !Ref AWS::NoValue

Outputs:
  # same as "AutoScalingGroupName"
  AsgLogicalId:
    Value: !Ref ASG
