---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Blizzard node (amd64)"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  Id:
    Type: String
    Description: Unique identifier, prefix for all resources created below.

  NodeKind:
    Type: String
    AllowedValues: ["worker"]
    Description: Node kind.

  S3BucketName:
    Type: String
    Description: S3 bucket name.

  Ec2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 SSH key name

  InstanceProfileArn:
    Type: String
    Description: Instance profile ARN

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The public subnet IDs where node instances are to be created.

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: EC2 security group ID

  ImageId:
    Type: String
    Default: ""
    Description: (Optional) Custom image ID. This value overrides any AWS Systems Manager Parameter Store value specified above.

  # https://ubuntu.com/server/docs/cloud-images/amazon-ec2
  # TODO: support arm64
  ImageIdSsmParameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID.

  Arch:
    Type: String
    Default: "amd64"
    Description: The name of the architecture.

  # Avalanche consensus paper used "c5.large" for testing 125 ~ 2,000 nodes
  # Avalanche test net ("fuji") runs "c5.2xlarge"
  #
  # https://aws.amazon.com/ec2/instance-types/c6a/
  # c6a.large:   2  vCPU + 4  GiB RAM
  # c6a.xlarge:  4  vCPU + 8  GiB RAM
  # c6a.2xlarge: 8  vCPU + 16 GiB RAM
  # c6a.4xlarge: 16 vCPU + 32 GiB RAM
  # c6a.8xlarge: 32 vCPU + 64 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/m6a/
  # m6a.large:   2  vCPU + 8  GiB RAM
  # m6a.xlarge:  4  vCPU + 16 GiB RAM
  # m6a.2xlarge: 8  vCPU + 32 GiB RAM
  # m6a.4xlarge: 16 vCPU + 64 GiB RAM
  # m6a.8xlarge: 32 vCPU + 128 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/m5/
  # m5.large:   2  vCPU + 8  GiB RAM
  # m5.xlarge:  4  vCPU + 16 GiB RAM
  # m5.2xlarge: 8  vCPU + 32 GiB RAM
  # m5.4xlarge: 16 vCPU + 64 GiB RAM
  # m5.8xlarge: 32 vCPU + 128 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/c5/
  # c5.large:   2  vCPU + 4  GiB RAM
  # c5.xlarge:  4  vCPU + 8  GiB RAM
  # c5.2xlarge: 8  vCPU + 16 GiB RAM
  # c5.4xlarge: 16 vCPU + 32 GiB RAM
  # c5.9xlarge: 32 vCPU + 72 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/r5/
  # r5.large:   2  vCPU + 16 GiB RAM
  # r5.xlarge:  4  vCPU + 32 GiB RAM
  # r5.2xlarge: 8  vCPU + 64 GiB RAM
  # r5.4xlarge: 16 vCPU + 128 GiB RAM
  # r5.8xlarge: 32 vCPU + 256 GiB RAM
  #
  # https://aws.amazon.com/ec2/instance-types/t3/
  # t3.large:    2  vCPU + 8 GiB RAM
  # t3.xlarge:   4  vCPU + 16 GiB RAM
  # t3.2xlarge:  8  vCPU + 32 GiB RAM
  #
  InstanceTypes:
    Type: CommaDelimitedList
    Default: c6a.2xlarge,m6a.2xlarge,m5.2xlarge,c5.2xlarge
    Description: EC2 instance types

  InstanceTypesCount:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 4
    Description: The number of instance types

  AsgMinInstancesInService:
    Type: Number
    Description: Minimum instances in service for update.
    Default: 1
    MinValue: 1
    MaxValue: 1000

  AsgMinSize:
    Type: Number
    Description: Minimum size auto scaling group
    Default: 1
    MinValue: 0
    MaxValue: 1000

  AsgMaxSize:
    Type: Number
    Description: Maximum size auto scaling group
    Default: 2
    MinValue: 1
    MaxValue: 1000

  AsgDesiredCapacity:
    Type: Number
    Description: Desired size auto scaling group
    Default: 1
    MinValue: 1
    MaxValue: 1000

  AsgSpotInstance:
    Type: String
    AllowedValues: [true, false]
    Default: false
    Description: Set to "true" if the EC2 instance is set up with spot instance.

  OnDemandPercentageAboveBaseCapacity:
    Type: Number
    Default: 100
    MinValue: 0
    MaxValue: 100
    Description: 0 for Spot only. 100 for On-Demand only.

  BlizzardDownloadSource:
    Type: String
    Default: "github"
    Description: (Optional) set to "github" to download from github, or download from S3.

Conditions:
  HasImageId:
    Fn::Not:
      - Fn::Equals:
          - Ref: ImageId
          - ""

  Has2InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 2
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has3InstanceTypes:
    Fn::Or:
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 3
      - Fn::Equals:
          - Ref: InstanceTypesCount
          - 4

  Has4InstanceTypes:
    Fn::Equals:
      - Ref: InstanceTypesCount
      - 4

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Join ["-", [!Ref Id, !Ref NodeKind, !Ref Arch]]
      LaunchTemplateData:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-iaminstanceprofile.html
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        ImageId:
          Fn::If:
            - HasImageId
            - !Ref ImageId
            - !Ref ImageIdSsmParameter
        KeyName: !Ref Ec2KeyPairName

        # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping.html
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumesize
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
        # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html
        BlockDeviceMappings:
          # mounted to "/dev/root"
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeType: gp3
              VolumeSize: 200

        Monitoring:
          Enabled: true

        # need this for public DNS + SSH access
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - !Ref SecurityGroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub "${Id}-${NodeKind}-${Arch}" }

        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-userdata
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
        # /var/log/cloud-init-output.log
        # takes about 3-minute
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              set -xeu

              export DEBIAN_FRONTEND=noninteractive
              sudo apt-get update -yqq && sudo apt-get upgrade -yqq \
              && sudo apt-get install -yq \
                  curl wget unzip zip gzip tar libssl-dev \
                  python3-pip python-setuptools zsh

              curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscli.v2.zip
              unzip awscli.v2.zip
              sudo ./aws/install
              /usr/local/bin/aws --version

              # https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu.html
              sudo snap install amazon-ssm-agent --classic
              sudo systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
              sudo systemctl restart snap.amazon-ssm-agent.amazon-ssm-agent.service
              mkdir -p /etc/systemd/system/snap.amazon-ssm-agent.amazon-ssm-agent.service.d
              cat > /etc/systemd/system/snap.amazon-ssm-agent.amazon-ssm-agent.service.d/10-restart-always.conf <<EOF
              [Service]
              Restart=always
              RestartSec=60s
              EOF
              sudo systemctl start --no-block snap.amazon-ssm-agent.amazon-ssm-agent.service

              if [[ ${BlizzardDownloadSource} == "github" ]]; then
                # TODO: support ARM64
                wget https://github.com/ava-labs/avalanche-ops/releases/download/latest/blizzard-aws.x86_64-unknown-linux-gnu
                mv ./blizzard-aws.x86_64-unknown-linux-gnu /tmp/blizzard
                chmod +x /tmp/blizzard
                sudo mv /tmp/blizzard /usr/local/bin/blizzard
              else
                aws s3 cp s3://${S3BucketName}/${Id}/install/blizzard /tmp/blizzard
                chmod +x /tmp/blizzard
                sudo mv /tmp/blizzard /usr/local/bin/blizzard
              fi;
              /usr/local/bin/blizzard --version

              cat > /tmp/blizzard.service <<EOF
              [Unit]
              Description=Blizzard

              [Service]
              Type=exec
              TimeoutStartSec=300
              Restart=on-failure
              RestartSec=5s
              LimitNOFILE=40000
              ExecStart=/usr/local/bin/blizzard
              StandardOutput=append:/var/log/blizzard.log
              StandardError=append:/var/log/blizzard.log

              [Install]
              WantedBy=multi-user.target
              EOF
              sudo mv /tmp/blizzard.service /etc/systemd/system/blizzard.service
              sudo systemctl daemon-reload
              sudo systemctl enable blizzard.service
              sudo systemctl start --no-block blizzard.service

              # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
              mkdir -p /tmp/install-cloudwatch-logs
              pushd /tmp/install-cloudwatch-logs
              wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/${Arch}/latest/amazon-cloudwatch-agent.deb
              sudo dpkg -i -E ./amazon-cloudwatch-agent.deb
              popd

              # enough time for "blizzard" to initialize cloudwatch configuration
              sleep 10
              echo "wait until /opt/aws/amazon-cloudwatch-agent/bin/config.json is written by blizzard"
              while [[ ! -s /opt/aws/amazon-cloudwatch-agent/bin/config.json ]]
                do
                echo "waiting for /opt/aws/amazon-cloudwatch-agent/bin/config.json creation"
                sleep 5
              done

              cat /opt/aws/amazon-cloudwatch-agent/bin/config.json
              /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
              mkdir -p /etc/systemd/system/amazon-cloudwatch-agent.service.d
              cat <<EOF > /etc/systemd/system/amazon-cloudwatch-agent.service.d/10-restart-always.conf
              [Service]
              Restart=always
              RestartSec=60s
              EOF

              sudo timedatectl set-ntp on

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref AsgMinInstancesInService
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Properties:
      AutoScalingGroupName: !Join ["-", [!Ref Id, !Ref NodeKind, !Ref Arch]]
      MinSize: !Ref AsgMinSize
      MaxSize: !Ref AsgMaxSize
      DesiredCapacity: !Ref AsgDesiredCapacity
      VPCZoneIdentifier: !Ref PublicSubnetIds
      HealthCheckType: EC2
      HealthCheckGracePeriod: 120
      MetricsCollection:
        - Granularity: "1Minute"
      Tags:
        # we can either propagate these information
        # via tags, blizzard CLI flags, blizzardup spec, etc.
        # use tags for relatively static configurations
        - Key: Name
          PropagateAtLaunch: true
          Value: !Join ["-", [!Ref Id, !Ref NodeKind, !Ref Arch]]
        - Key: ID
          PropagateAtLaunch: true
          Value: !Ref Id
        - Key: ARCH_TYPE
          PropagateAtLaunch: true
          Value: amd64
        - Key: OS_TYPE
          PropagateAtLaunch: true
          Value: linux
        - Key: ASG_SPOT_INSTANCE
          PropagateAtLaunch: true
          Value: !Ref AsgSpotInstance
        - Key: NODE_KIND
          PropagateAtLaunch: true
          Value: !Ref NodeKind
        - Key: S3_BUCKET_NAME
          PropagateAtLaunch: true
          Value: !Ref S3BucketName
        - Key: CLOUDWATCH_CONFIG_FILE_PATH
          PropagateAtLaunch: true
          Value: /opt/aws/amazon-cloudwatch-agent/bin/config.json
        - Key: BLIZZARDUP_SPEC_PATH
          PropagateAtLaunch: true
          Value: /data/blizzardup.yaml

      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-mixedinstancespolicy.html
      # https://aws.amazon.com/getting-started/hands-on/ec2-auto-scaling-spot-instances/
      MixedInstancesPolicy:
        # define balance between spot vs. on-demand
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-instancesdistribution.html
        # https://ec2spotworkshops.com/launching_ec2_spot_instances/asg.html
        InstancesDistribution:
          OnDemandAllocationStrategy: "lowest-price"
          # minimum amount of the Auto Scaling group's capacity that must be fulfilled by On-Demand Instances
          OnDemandBaseCapacity: 0
          # percentages of On-Demand Instances and Spot Instances for your additional capacity beyond OnDemandBaseCapacity
          # 20 specifies 20% On-Demand Instances, 80% Spot Instances
          # If set to 0, only Spot Instances are used.
          # If set to 100, only On-Demand Instances are used.
          OnDemandPercentageAboveBaseCapacity: !Ref OnDemandPercentageAboveBaseCapacity
          SpotAllocationStrategy: "lowest-price"
          # number of Spot Instance pools across which to allocate your Spot Instances
          SpotInstancePools: 3
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplate.html
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref ASGLaunchTemplate
            Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplateoverrides.html
          Overrides:
            - InstanceType: !Select [0, !Ref InstanceTypes]
            - Fn::If:
                - Has2InstanceTypes
                - InstanceType: !Select [1, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has3InstanceTypes
                - InstanceType: !Select [2, !Ref InstanceTypes]
                - !Ref AWS::NoValue
            - Fn::If:
                - Has4InstanceTypes
                - InstanceType: !Select [3, !Ref InstanceTypes]
                - !Ref AWS::NoValue

Outputs:
  # same as "AutoScalingGroupName"
  AsgLogicalId:
    Value: !Ref ASG
