#!/usr/bin/env bash
set -xue

if ! [[ "$0" =~ scripts/avalanchego-compatibility.node-id.sh ]]; then
  echo "must be run from repository root"
  exit 255
fi

###
pushd ./avalanchego-compatibility
go run \
./key/main.go > /tmp/test.key.json
popd
cargo run --example key -- /tmp/test.key.json

###
rm -f /tmp/test.insecure.key /tmp/test.insecure.cert
cargo run --example cert -- /tmp/test.insecure.key /tmp/test.insecure.cert

pushd ./avalanchego-compatibility
go run ./load-node-id/main.go /tmp/test.insecure.key /tmp/test.insecure.cert

# copied from "avalanchego/staking/local/staking1.key,crt"
go run \
./load-node-id/main.go \
../artifacts/staker1.insecure.key ../artifacts/staker1.insecure.crt
go run \
./load-node-id/main.go \
../artifacts/staker2.insecure.key ../artifacts/staker2.insecure.crt
go run \
./load-node-id/main.go \
../artifacts/staker3.insecure.key ../artifacts/staker3.insecure.crt
go run \
./load-node-id/main.go \
../artifacts/staker4.insecure.key ../artifacts/staker4.insecure.crt
go run \
./load-node-id/main.go \
../artifacts/staker5.insecure.key ../artifacts/staker5.insecure.crt

# generated by "examples/cert.rs"
go run \
./load-node-id/main.go \
../artifacts/test.insecure.key ../artifacts/test.insecure.crt

popd

###
echo "ALL SUCCESS!"
