#!/usr/bin/env bash
set -xue

if ! [[ "$0" =~ scripts/avalanchego-compatibility.node-id.sh ]]; then
  echo "must be run from repository root"
  exit 255
fi

rm -f /tmp/test.insecure.key /tmp/test.insecure.cert
cargo run --example cert -- /tmp/test.insecure.key /tmp/test.insecure.cert

pushd ./avalanchego-compatibility
go run ./load-node-id/main.go /tmp/test.insecure.key /tmp/test.insecure.cert

# copied from "avalanchego/staking/local/staking1.key,crt"
go run \
./load-node-id/main.go \
../artifacts/staker1.insecure.key ../artifacts/staker1.insecure.crt

# generated by "examples/cert.rs"
go run \
./load-node-id/main.go \
../artifacts/test.insecure.key ../artifacts/test.insecure.crt

popd

echo "ALL SUCCESS!"
